In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from word2number import w2n

In [2]:
df=pd.read_csv('hiring.csv')
df

experience  test_score  interview_score   salary
0           8         9.0                9      NaN
1           8         6.0                6      NaN
2           5         6.0                7  60000.0
3           2        10.0               10  65000.0
4           7         9.0                6  70000.0
5           3         7.0               10  62000.0
6          10         NaN                7  72000.0
7          11         7.0                8  80000.0

In [3]:
df.test_score.median()

7.0

In [4]:
df.test_score=df.test_score.fillna(df.test_score.median())
df

experience  test_score  interview_score   salary
0           8         9.0                9      NaN
1           8         6.0                6      NaN
2           5         6.0                7  60000.0
3           2        10.0               10  65000.0
4           7         9.0                6  70000.0
5           3         7.0               10  62000.0
6          10         7.0                7  72000.0
7          11         7.0                8  80000.0

In [5]:
df.salary.median()

67500.0

In [6]:
df.salary=df.salary.fillna(df.salary.median())

In [7]:
df

experience  test_score  interview_score   salary
0           8         9.0                9  67500.0
1           8         6.0                6  67500.0
2           5         6.0                7  60000.0
3           2        10.0               10  65000.0
4           7         9.0                6  70000.0
5           3         7.0               10  62000.0
6          10         7.0                7  72000.0
7          11         7.0                8  80000.0

In [8]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df['salary'])

LinearRegression()

In [9]:
reg.predict([[5,6,7]])

array([62053.96772024])

In [11]:
reg.predict([[2,9,6]])

array([58842.88836584])

In [12]:
reg.predict([[12,10,10]])

array([82614.82851379])